# Generated by Django 3.1.1 on 2020-09-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionAnswers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
